name: "kDrive Backup Sync"
description: "Sync via S6 Service"
version: "1.0.8"
slug: "kdrive_backup"
arch:
  - aarch64
  - amd64
map:
  - backup:rw
options:
  kdrive_id: ""
  kdrive_token: ""
schema:
  kdrive_id: str
  kdrive_token: password